services:
  authserver-frontend:
    build: .
    # Unicamente dentro del Docker net
    # expose:
    #   - 3000
    # args:
    #   - REACT_APP_BACKEND=${REACT_APP_BACKEND}
    environment:
      - REACT_APP_BACKEND=${REACT_APP_BACKEND}
    ports:
      - "3000:3000"
    container_name: authserver-frontend
    restart: always
    networks:
      - authserver-network

  authserver-nginx:
    image: nginx:stable-alpine
    container_name: authserver-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - authserver-frontend
    networks:
      - authserver-network

networks:
  authserver-network:
    external: true